[workspace]
members = [
    "borsh",
    "borsh-derive",
    "borsh-derive-internal",
    "borsh-schema-derive-internal",
]
exclude = [ "fuzz/fuzz-run", "benchmarks" ]

[workspace.package]
# shared version of all public crates in the workspace
version = "0.10.4"
rust-version = "1.66.0"
